---
- name: collect output file of checking script
  hosts: WAS
  tasks:
  - name: get collect script
    find: 
      path: "{{ ansible_env.HOME }}"
      file_type: file
      patterns: '^collect_.*\_acc.sh$'
      use_regex: yes
    register: result_script
  - name: matching script file
    vars:
      msg: |
         Invalid matched scripts found:
         (1) No script found
         (2) More than one script found, please rename all unused script and try again
    fail: 
      msg: "{{ msg.split('\n') }}"
    when: result_script.matched != 1
  - name: get instance name
    set_fact: 
      instance: "{{ result_script.files.0.path | basename | regex_search('^collect_(.+)_acc.sh$', '\\1') | first | string }}"
  - name: running checking script
    shell: /bin/sh {{ result_script.files.0.path }}
  - name: get output file
    find: 
      path: "{{ ansible_env.HOME }}"
      file_type: file
      pattern: "{{ ansible_hostname | lower }}_{{ instance }}_*.txt"
      age: -3m
    register: result_files
  - name: validate script output
    fail:
      msg: "No file found, please ensure script output named as {{ ansible_hostname | lower }}_{{ instance }}_*.txt"
    when: result_files.matched == 0
  - name: download output file to local
    fetch:
      src: "{{ item.path }}"
      dest: /Apps/reports/was/{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}/
      flat: yes
    with_items: "{{ result_files.files }}"
