#
# Restore volume with given snaphot name on Netapp storage
# 
# Author: Systex PS
# Last updated: 12 Nov 2021
# Version: 1.0
#
# Testing backgroup:
#     - Netapp ontap: 9.8P6
#     - OS Platform: Red Hat Enterprise Linux Server release 7.7 (Maipo)
#     - Ansible Tower: 3.7.3
#     - Ansible: 2.9.13
#     - Python: 3.6.9-2 
#
- name: Restore volume from snapshot copy on Netapp onatp
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - snapshotrestore
