---
- name: Log scanning and send email alert
  hosts: SV81154
  gather_facts: yes
  #become: no
  #become_method: sudo
  vars:
    instance: IHSMO 
  #vars_files:
  #  - varfile.yaml
  tasks:
  - name: Finding error message in log files
  #  shell: grep -m 5 -i 404 /opt/IBM/{{ instance }}/HTTPServer/logs/*.log
    shell: grep -m 5 'Restart your X session' /var/log/vmware-install.log
    register: result
    failed_when: "result.rc != 0"
  - name: result
    debug: 
      msg: "{{ result.stdout_lines }}" 
    when: "result.rc == 0"
  - name: sending alert email
    delegate_to: localhost
    mail:
      host: SLF-ANTISPAM.CA.SUNLIFE
      port: 25
      from: root@{{ ansible_hostname }}
#      to: ansadmin@sv81805
      to: hk_middleware@sunlife.com
      subject: testing from ansible
      body: "{{ result.stdout_lines }}"
